### ISSUE TITLE
Project Peer Review: billy-fishing.com

### ISSUE THREAD

**Issue by emilynsmith2** [MIS3690/WebTech#1]
Your website is really cool! I use to work at a restaurant in gloucester and fishermen would always come in and show me pics of their tunas, and their fresh cuts hahahah... now i know a lot more about what it takes to actually catch tuna!!
Technical:
1. maybe add padding to the images
2. maybe make the top line of your table bold
Content:
1. A chart showing how much it would cost for everything would be interesting to see
2. A video showing a clip of tuna fishing would be cool too

**Comment by lzblack** [comment]
Please commend in the project repository, not here.
